### ISSUE TITLE
Null/Error Codes

### ISSUE THREAD

**Issue by blueberrie231** [maxrave-dev/SimpMusic#405] opened 2024-06-24 14:27 UTC
Hiya, every time I try to open a playlist either from my imported YouTube playlists or suggested from the app it says it can't open it and there's an error code.

**Comment by WHONEYR** [comment] 2024-06-25 00:04
Yeah this also happen with albums

**Comment by sirdx** [comment] 2024-06-25 06:26
Duplicate of #401

**Comment by maxrave-dev** [comment] 2024-06-25 16:19
Fixed f7959f33aa746cf88a17403a4539d0c10b4e02d7

**Closed by maxrave-dev** 2024-06-25 16:19 UTC
