### ISSUE TITLE
YouTube playlists not downloading

### ISSUE THREAD

**Issue by PetrNebukin** [maxrave-dev/SimpMusic#498] opened 2024-08-13 23:30 UTC
**Description**
When trying to download an online YT playlist, **in which at least one track has been downloaded previously**, says that the entire playlist has been downloaded previously. However, if you add the playlist to the list of local playlists and try to download it, this problem does not occur.

**Reproduction**
1. Go to Library
2. Go to any playlist, which has at least one previously downloaded track
3. Take a look or try to click the download button
4. See problem?

**Attention!**
This problem occurs not always, most often, completely closing the application and restarting it helps

**Comment by Iliano101** [comment] 2024-08-14 03:02
Duplicate of #493

**Closed** 2024-08-15 21:23 UTC
