### ISSUE TITLE
Cannot open playlist

### ISSUE THREAD

**Issue by LaKinguin** [maxrave-dev/SimpMusic#413] opened 2024-06-27 13:21 UTC
I cant open the playlist it just gives me an error. ![Screenshot_20240627-212144.png](https://github.com/maxrave-dev/SimpMusic/assets/172463985/08e1b10b-0c96-4614-815c-f50c2d848fdc)

**Comment by ddavidd** [comment] 2024-06-27 14:37
This is a duplicate of #401 and it was patched in c87312b

**Closed** 2024-07-02 09:49 UTC
